### ISSUE TITLE
[ENH] Maybe add some physio processing?

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/xcp_d#455] opened 2022-09-01 19:05 UTC
Things to look into:
================
 * phys2denoise

**Comment by tsalo** [comment] 2022-09-16 15:36
A few thoughts on physio processing/denoising:

1. I believe that physio folks generally recommend performing manual QC (e.g., errant peak/trough labeling) before using the physio data for denoising. BIDS-raw doesn't include any QC derivatives, and I'm not sure if the physio community (e.g., the `physiopy` organization) has converged on a BIDS-like structure for those derivatives. Might be worth checking with them about a preferred format for that stuff, so `xcp_d` can just load them like any other derivative.
2. There are many, many physio denoising strategies. `phys2denoise` can calculate several nuisance regressors, but I'm not sure which ones would be most useful in `xcp_d`.
3. There might be a chance to use physio data in conjunction with [`rapidtide`](https://rapidtide.readthedocs.io/en/latest/) or [`happy`](https://rapidtide.readthedocs.io/en/latest/usage.html#happy).

**Comment by tsalo** [comment] 2022-10-14 13:30
One workaround may be to allow multiple custom confounds. For example, users could provide the task-regressor time series, along with the phys2denoise output as well. We might need to support config files or something, to only grab the right columns from the additional confounds files.

**Comment by mattcieslak** [comment] 2022-10-14 13:44
We might need to put together an entirely separate workflow because RETROICOR needs the data before any spatial resampling has occurred.

**Comment by tsalo** [comment] 2022-10-14 14:15
That's a good point. I was thinking more of metrics like respiratory variance (RV) or respiration volume-per-time (RVT). RETROICOR and other voxel-wise denoising approaches will require a lot more thought.

At the moment, I don't think phys2denoise implements RETROICOR, but it is almost certainly on the roadmap.

**Comment by tsalo** [comment] 2023-01-04 19:17
It looks like RETROICOR needs to be run (including the regression) before slice timing correction, so I think it falls outside of xcp-d's scope. Generic physiological regressors, like RVT and RV, can definitely be used, but I think the custom confounds infrastructure already supports them.

**Comment by tsalo** [comment] 2023-01-16 15:15
Closing this in favor of #749.

**Closed by tsalo** 2023-01-16 15:15 UTC
Labels: enhancement
